apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
      - name: server
        image: drone/drone:0.7
        imagePullPolicy: Always
        env:
          - name: "DRONE_HOST"
            value: drone
          - name: "DRONE_OPEN"
            value: "true"
          - name: "DRONE_GITHUB"
            value: "true"
          - name: "DRONE_GITHUB_CLIENT"
            value:
          - name: "DRONE_GITHUB_SECRET"
            value:
          - name: "DRONE_SECRET"
            value: emc-preso
        volumeMounts:
        - mountPath: /var/lib/drone
          name: drone-lib
      volumes:
      - name: drone-lib
        hostPath:
          path: /var/lib/drone
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    name: server
